export type TModel = {
    modelId: number;
    brandId: number;
    eModel: string | null;
    gModel: string | null;
    fModel: string | null;
    sModel: string | null;
    iModel: string | null;
    jModel: string | null;
    swModel: string | null;
    bModel: string | null;
    eExtraInfo: string | null;
    gExtraInfo: string | null;
    fExtraInfo: string | null;
    sExtraInfo: string | null;
    iExtraInfo: string | null;
    jExtraInfo: string | null;
    swExtraInfo: string | null;
    bExtraInfo: string | null;
    eShortModel: string | null;
    gShortModel: string | null;
    fShortModel: string | null;
    sShortModel: string | null;
    iShortModel: string | null;
    jShortModel: string | null;
    swShortModel: string | null;
    bShortModel: string | null;
    debug_string: string | null;
    debug_sort_string: string | null;
};
