codecov:
    require_ci_to_pass: false

comment:
    show_carryforward_flags: true

flags:
    database:
        paths:
            - packages/database/**
        carryforward: false
    gateway:
        paths:
            - packages/gateway/**
        carryforward: false
    lobby:
        paths:
            - packages/lobby/**
        carryforward: false
    login:
        paths:
            - packages/login/**
        carryforward: false
    patch:
        paths:
            - packages/patch/**
        carryforward: false
    persona:
        paths:
            - packages/persona/**
        carryforward: false
    shard:
        paths:
            - packages/shard/**
        carryforward: false
    shared:
        paths:
            - packages/shared/**
        carryforward: false
    transactions:
        paths:
            - packages/transactions/**
        carryforward: false
    interfaces:
        paths:
            - packages/interfaces/**
        carryforward: false
    core:
        paths:
            - packages/core/**
        carryforward: false

component_management:
    individual_components:
        - component_id: components_team1
          name: Team 1
          paths:
              - packages/core/**
              - packages/gateway/**
              - packages/shared/**

coverage:
    status:
        project:
            default:
                removed_code_behavior: adjust_base
