codecov:
    require_ci_to_pass: false

ai_pr_review:
    enabled: true

comment:
    show_carryforward_flags: true

flags:
    cli:
        paths:
            - packages/cli/**
        carryforward: true
    connection:
        paths:
            - packages/connection/**
        carryforward: true
    database:
        paths:
            - packages/database/**
        carryforward: true
    gateway:
        paths:
            - packages/gateway/**
        carryforward: true
    mcots:
        paths:
            - packages/mcots/**
        carryforward: true
    nps:
        paths:
            - packages/nps/**
        carryforward: true
    patch:
        paths:
            - packages/patch/**
        carryforward: true
    shard:
        paths:
            - packages/shard/**
        carryforward: true
    shared:
        paths:
            - packages/shared/**
        carryforward: true
    shared-packets:
        paths:
            - packages/shared-packets/**
        carryforward: true

component_management:
    individual_components:
        - component_id: components_nps
          name: NPS
          paths:
              - packages/cli/**
              - packages/connection/**
              - packages/database/**
              - packages/gateway/**
              - packages/lobby/**
              - packages/login/**
              - packages/nps/**
              - packages/patch/**
              - packages/persona/**
              - packages/shard/**
              - packages/shared-packets/**
        - component_id: components_mcots
          name: MCOTS
          paths:
              - packages/cli/**
              - packages/connection/**
              - packages/database/**
              - packages/gateway/**
              - packages/mcots/**
              - packages/shared-packets/**

ignore:
    - "**/__generated__/**"
