import { player as playerSchema } from "rusty-motors-schema";

const playerCsvHeader = [
    "player_id",
    "customer_id",
    "player_type_id",
    "sanctioned_score",
    "challenge_score",
    "last_logged_in",
    "times_logged_in",
    "bank_balance",
    "num_cars_owned",
    "is_logged_in",
    "driver_style",
    "lp_code",
    "lp_text",
    "car_num_1",
    "car_num_2",
    "car_num_3",
    "car_num_4",
    "car_num_5",
    "car_num_6",
    "dl_number",
    "persona",
    "address",
    "residence",
    "vehicle_id",
    "current_race_id",
    "offline_driver_skill",
    "offline_grudge",
    "offline_reputation",
    "total_time_played",
    "car_info_setting",
    "stock_classic_class",
    "stock_muscle_class",
    "modified_classic_class",
    "modified_muscle_class",
    "outlaw_class",
    "drag_class",
    "challenge_rung",
    "offline_ai_car_class",
    "offline_ai_skin_id",
    "offline_ai_car_bpt_id",
    "offline_ai_state",
    "bodytype",
    "skin_color",
    "hair_color",
    "shirt_color",
    "pants_color",
    "offline_driver_style",
    "offline_driver_attitude",
    "evaded_fuzz",
    "pinks_won",
    "num_unread_mail",
    "total_races_run",
    "total_races_won",
    "total_races_completed",
    "total_winnings",
    "insurance_risk_points",
    "insurance_rating",
    "challenge_races_run",
    "challenge_races_won",
    "challenge_races_completed",
    "cars_lost",
    "cars_won",
];

const playerCsvRow = [
    [
        6,
        0,
        1,
        0,
        0,
        new Date(0),
        0,
        999999,
        0,
        0,
        0,
        0,
        null,
        0,
        0,
        0,
        0,
        0,
        0,
        "xxx",
        "All Factory Ford",
        "1240 A Street",
        "ABCDEFGHIJKLMNOPQRST",
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
    ],
];

export function csvRowToPlayer(row: (string | number | Date | null)[]): typeof playerSchema.$inferSelect {
    return {
        playerId: row[0] as number,
        customerId: row[1] as number,
        playerTypeId: row[2] as number,
        sanctionedScore: row[3] as number,
        challengeScore: row[4] as number,
        lastLoggedIn: row[5] as Date,
        timesLoggedIn: row[6] as number,
        bankBalance: row[7] as number,
        numCarsOwned: row[8] as number,
        isLoggedIn: row[9] as number,
        driverStyle: row[10] as number,
        lpCode: row[11] as number,
        lpText: row[12] as string | null,
        carNum1: row[13] as string,
        carNum2: row[14] as string,
        carNum3: row[15] as string,
        carNum4: row[16] as string,
        carNum5: row[17] as string,
        carNum6: row[18] as string,
        dlNumber: row[19] as string,
        persona: row[20] as string,
        address: row[21] as string,
        residence: row[22] as string,
        vehicleId: row[23] as number | null,
        currentRaceId: row[24] as number | null,
        offlineDriverSkill: row[25] as number | null,
        offlineGrudge: row[26] as number | null,
        offlineReputation: row[27] as number | null,
        totalTimePlayed: row[28] as number | null,
        carInfoSetting: row[29] as number | null,
        stockClassicClass: row[30] as number | null,
        stockMuscleClass: row[31] as number | null,
        modifiedClassicClass: row[32] as number | null,
        modifiedMuscleClass: row[33] as number | null,
        outlawClass: row[34] as number | null,
        dragClass: row[35] as number | null,
        challengeRung: row[36] as number | null,
        offlineAiCarClass: row[37] as number | null,
        offlineAiSkinId: row[38] as number | null,
        offlineAiCarBptId: row[39] as number | null,
        offlineAiState: row[40] as number | null,
        bodytype: row[41] as number | null,
        skinColor: row[42] as number | null,
        hairColor: row[43] as number | null,
        shirtColor: row[44] as number | null,
        pantsColor: row[45] as number | null,
        offlineDriverStyle: row[46] as number | null,
        offlineDriverAttitude: row[47] as number | null,
        evadedFuzz: row[48] as number | null,
        pinksWon: row[49] as number | null,
        numUnreadMail: row[50] as number | null,
        totalRacesRun: row[51] as number | null,
        totalRacesWon: row[52] as number | null,
        totalRacesCompleted: row[53] as number | null,
        totalWinnings: row[54] as number | null,
        insuranceRiskPoints: row[55] as number | null,
        insuranceRating: row[56] as number | null,
        challengeRacesRun: row[57] as number | null,
        challengeRacesWon: row[58] as number | null,
        challengeRacesCompleted: row[59] as number | null,
        carsLost: row[60] as number | null,
        carsWon: row[61] as number | null,
    };
}

for (const row of playerCsvRow) {
    if (row.length !== playerCsvHeader.length) {
        throw new Error(`Row length does not match header length: got ${row.length}, expected ${playerCsvHeader.length}`);
    }

    const player = [csvRowToPlayer(row.map((value, index) => {
        if (typeof value === "undefined") {
            throw new Error(`Undefined value at index ${playerCsvHeader[index]}`);
        }

        return value;
    }))];
}
