CREATE TABLE "sessions"
(
   customer_id serial,
   session_key character(20)  NOT NULL,
   s_key character(20)  NOT NULL,
   context_id character(20)  NOT NULL,
   connection_id character(20)  NOT NULL,
   CONSTRAINT pk_session PRIMARY KEY (customer_id)
)
WITH (
  OIDS = FALSE
);

CREATE TABLE "lobbies"
(
			lobbyID integer, 
      raceTypeID integer, 
      turfID integer, 
      riffName character(32), 
      eTurfName character(256), 
      clientArt character(11), 
      elementID integer, 
			turfLength integer, 
      startSlice integer, 
      endSlice integer, 
      dragStageLeft real, 
      dragStageRight real, 
      dragStagingSlice integer, 
			gridSpreadFactor real, 
      linear smallint, 
      numPlayersMin smallint, 
      numPlayersMax smallint, 
      numPlayersDefault smallint, 
			bnumPlayersEnabled smallint, 
      numLapsMin smallint, 
      numLapsMax smallint, 
      numLapsDefault smallint, 
      bNumLapsEnabled smallint, 
      numRoundsMin smallint, 
      numRoundsMax smallint, 
			numRoundsDefault smallint, 
      bNumRoundsEnabled smallint, 
      bWeatherDefault smallint, 
      bWeatherEnabled smallint, 
      bNightDefault smallint, 
			bNightEnabled smallint, 
      bBackwardDefault smallint, 
      bBackwardEnabled smallint, 
      bTrafficDefault smallint, 
      bTrafficEnabled smallint, 
			bDamageDefault smallint, 
      bDamageEnabled smallint, 
      bAIDefault smallint, 
      bAIEnabled smallint, 
      topDog character(13), 
      turfOwner character(33), 
      qualifyingTime integer, 
			clubNumPlayers, 
      clubNumLaps, 
      clubNumRounds, 
      bClubNight, 
      bClubWeather, 
      bClubBackwards, 
      topSeedsMPS, 
			lobbyDifficulty, 
      ttPointForQualify, 
      ttCashForQualify, 
      ttPointBonusFasterIncs, 
      ttCashBonusFasterIncs, 
			ttTimeIncrements, 
      victoryPoints[1], 
      victoryCash[1], 
      victoryPoints[2], 
      victoryCash[2], 
      victoryPoints[3],
			victoryCash[3], 
      minLevel, 
      minResetSlice, 
      maxResetSlice, 
      bnewbieFlag, 
      bdriverHelmetFlag,
			clubNumPlayersMax, 
      clubNumPlayersMin, 
      clubNumPlayersDefault, 
      numClubsMax, 
      numClubsMin,
			racePointsFactor, 
      bodyClassMax, 
      powerClassMax, 
      clubLogoID, 
      teamtWeather, 
      teamtNight,
			teamtBackwards, 
      teamtNumLaps, 
      teamtBaseTUP, 
      raceCashFactor

)
WITH (
  OIDS = FALSE
);
 
