CREATE TABLE PartGrade (
	PartGradeID INTEGER NOT NULL,
	EText VARCHAR(50),
	GText VARCHAR(50),
	FText VARCHAR(50),
	PartGrade VARCHAR(50),
	CONSTRAINT SYS_PK_11985 PRIMARY KEY (PartGradeID)
);
CREATE UNIQUE INDEX SYS_IDX_SYS_PK_11985_11986 ON PartGrade (PartGradeID);