CREATE TABLE Vehicle (
	VehicleID INTEGER NOT NULL,
	SkinID INTEGER NOT NULL,
	Flags INTEGER NOT NULL,
	Class SMALLINT NOT NULL,
	InfoSetting SMALLINT NOT NULL,
	DamageInfo bytea,
	DamageCached INTEGER DEFAULT 0,
	CONSTRAINT SYS_PK_12214 PRIMARY KEY (VehicleID),
	CONSTRAINT VEHICLE_PARTVEHICLE FOREIGN KEY (VehicleID) REFERENCES Part(PartID) ON DELETE CASCADE,
	CONSTRAINT VEHICLE_PTSKINVEHICLE FOREIGN KEY (SkinID) REFERENCES PTSkin(SkinID)
);
CREATE UNIQUE INDEX SYS_IDX_SYS_PK_12214_12215 ON Vehicle (VehicleID);
CREATE INDEX SYS_IDX_VEHICLE_PARTVEHICLE_12844 ON Vehicle (VehicleID);
CREATE INDEX SYS_IDX_VEHICLE_PTSKINVEHICLE_12856 ON Vehicle (SkinID);