CREATE TABLE SVA_CarClass (
	SVA_CarClass INTEGER DEFAULT 0 NOT NULL,
	Description VARCHAR(50),
	CONSTRAINT SYS_PK_12175 PRIMARY KEY (SVA_CarClass)
);
CREATE UNIQUE INDEX SYS_IDX_SYS_PK_12175_12176 ON SVA_CarClass (SVA_CarClass);
