CREATE TABLE PlayerType (
	PlayerTypeID INTEGER NOT NULL,
	PlayerType VARCHAR(100) NOT NULL,
	CONSTRAINT SYS_PK_12040 PRIMARY KEY (PlayerTypeID)
);
CREATE UNIQUE INDEX SYS_IDX_SYS_PK_12040_12041 ON PlayerType (PlayerTypeID);