CREATE TABLE Part (
	PartID INTEGER NOT NULL,
	ParentPartID INTEGER,
	BrandedPartID INTEGER NOT NULL,
	PercentDamage SMALLINT NOT NULL,
	ItemWear INTEGER NOT NULL,
	AttachmentPointID INTEGER,
	OwnerID INTEGER,
	PartName VARCHAR(100),
	RepairCost INTEGER DEFAULT 0,
	ScrapValue INTEGER DEFAULT 0,
	CONSTRAINT SYS_PK_11976 PRIMARY KEY (PartID),
	CONSTRAINT PART_BRANDEDPARTPART FOREIGN KEY (BrandedPartID) REFERENCES BrandedPart(BrandedPartID),
	CONSTRAINT PART_R25 FOREIGN KEY (ParentPartID) REFERENCES Part(PartID),
	CONSTRAINT PART_R9 FOREIGN KEY (AttachmentPointID) REFERENCES AttachmentPoint(AttachmentPointID)
);
CREATE INDEX SYS_IDX_PART_BRANDEDPARTPART_12431 ON Part (BrandedPartID);
CREATE INDEX SYS_IDX_PART_R25_15192 ON Part (ParentPartID);
CREATE INDEX SYS_IDX_PART_R9_12442 ON Part (AttachmentPointID);
CREATE UNIQUE INDEX SYS_IDX_SYS_PK_11976_11977 ON Part (PartID);
