CREATE TABLE SkinType (
	SkinTypeID INTEGER NOT NULL,
	SkinType VARCHAR(100),
	CONSTRAINT SYS_PK_12138 PRIMARY KEY (SkinTypeID)
);
CREATE UNIQUE INDEX SYS_IDX_SYS_PK_12138_12139 ON SkinType (SkinTypeID);