CREATE TABLE StockAssembly (
	ParentBrandedPartID INTEGER NOT NULL,
	ChildBrandedPartID INTEGER NOT NULL,
	AttachmentPointID INTEGER NOT NULL,
	ConfigDefault SMALLINT NOT NULL,
	PhysicsDefault SMALLINT NOT NULL,
	CONSTRAINT SYS_PK_12146 PRIMARY KEY (ParentBrandedPartID,ChildBrandedPartID,AttachmentPointID),
	CONSTRAINT STOCKASSEMBLY_ATTACHMENTPOINTSTOCKASSEMBLY FOREIGN KEY (AttachmentPointID) REFERENCES AttachmentPoint(AttachmentPointID),
	CONSTRAINT STOCKASSEMBLY_BRANDEDPARTSTOCKASSEMBLY FOREIGN KEY (ChildBrandedPartID) REFERENCES BrandedPart(BrandedPartID),
	CONSTRAINT STOCKASSEMBLY_BRANDEDPARTSTOCKASSEMBLY1 FOREIGN KEY (ParentBrandedPartID) REFERENCES BrandedPart(BrandedPartID)
);
CREATE INDEX SYS_IDX_STOCKASSEMBLY_ATTACHMENTPOINTSTOCKASSEMBLY_12750 ON StockAssembly (AttachmentPointID);
CREATE INDEX SYS_IDX_STOCKASSEMBLY_BRANDEDPARTSTOCKASSEMBLY1_12774 ON StockAssembly (ParentBrandedPartID);
CREATE INDEX SYS_IDX_STOCKASSEMBLY_BRANDEDPARTSTOCKASSEMBLY_12762 ON StockAssembly (ChildBrandedPartID);
CREATE UNIQUE INDEX SYS_IDX_SYS_PK_12146_12147 ON StockAssembly (ParentBrandedPartID,ChildBrandedPartID,AttachmentPointID);