CREATE TABLE DriverClass (
	DriverClassID SMALLINT NOT NULL,
	DriverClass VARCHAR(50),
	CONSTRAINT SYS_PK_11831 PRIMARY KEY (DriverClassID)
);
CREATE UNIQUE INDEX SYS_IDX_SYS_PK_11831_11832 ON DriverClass (DriverClassID);