import { NPSMessage } from 'rusty-motors-shared';
import { getMessageHandlerOrFallback } from './internal.js';
import { getServerLogger, ServerLogger } from 'rusty-motors-logger';
import { GamePacket } from 'rusty-motors-shared-packets';
import { BytableMessage } from '@rustymotors/binary';

const defaultLogger = getServerLogger('LoginServer');

/**
 * Handles an incoming login data message by deserializing it and dispatching it to the appropriate handler.
 *
 * @param connectionId - The unique identifier for the client connection.
 * @param message - The incoming serialized login data message.
 * @returns An object containing the {@link connectionId} and an array of {@link GamePacket} messages generated by the handler.
 *
 * @throws {Error} If an error occurs during message deserialization or handler execution.
 */
export async function handleLoginData({
    connectionId,
    message,
    log = defaultLogger,
}: {
    connectionId: string;
    message: BytableMessage;
    log?: ServerLogger;
}): Promise<{
    connectionId: string;
    messages: GamePacket[];
}> {
    log.debug(`[${connectionId}] Entering handleLoginData`);

    // The packet needs to be an NPSMessage
    const inboundMessage = new NPSMessage();
    inboundMessage.deserialize(message.serialize());
    let messageHandler;

    messageHandler = getMessageHandlerOrFallback(message.header.messageId);

    try {
        const result = await messageHandler({
            connectionId,
            message,
            log,
        });
        log.debug(
            `[${connectionId}] Leaving handleLoginData with ${result.messages.length} messages`,
        );
        return {
            connectionId,
            messages: result.messages,
        };
    } catch (error) {
        const err = Error(`[${connectionId}] Error in login service`, {
            cause: error,
        });
        throw err;
    }
}
