/**
 * !!! This file is autogenerated do not edit by hand !!!
 *
 * Generated by: @databases/pg-schema-print-types
 * Checksum: 4F7qIfLDFaUNa+UpB5zv1oo5dQLYfT/Nyv4WWdHYycpa2Cd8U60HudGhGUikk6S2Ux1YFnwowfbpOewG2pObzA==
 */

/* eslint-disable */
// tslint:disable

interface AbstractPartType {
  abstract_part_type_id: number & {readonly __brand?: 'abstract_part_type_abstract_part_type_id'}
  baft: (string) | null
  /**
   * @default 0
   */
  block_family_compatibility: (number) | null
  but: (string) | null
  depends_on: (number) | null
  eapt: string
  eut: (string) | null
  faft: (string) | null
  fut: (string) | null
  gapt: (string) | null
  /**
   * @default 0
   */
  garage_category: (number) | null
  gut: (string) | null
  iaft: (string) | null
  iut: (string) | null
  jaft: (string) | null
  jut: (string) | null
  /**
   * @default 0
   */
  modified_rule: (number) | null
  parent_abstract_part_type_id: (number) | null
  part_filename: (string) | null
  /**
   * @default 0
   */
  part_paired: (number) | null
  /**
   * @default 0
   */
  repair_cost_modifier: (string) | null
  saft: (string) | null
  schematic_picname1: (string) | null
  schematic_picname2: (string) | null
  /**
   * @default 0
   */
  scrap_value_modifier: (string) | null
  sut: (string) | null
  sw_aft: (string) | null
  swut: (string) | null
}
export default AbstractPartType;

interface AbstractPartType_InsertParameters {
  abstract_part_type_id: number & {readonly __brand?: 'abstract_part_type_abstract_part_type_id'}
  baft?: (string) | null
  /**
   * @default 0
   */
  block_family_compatibility?: (number) | null
  but?: (string) | null
  depends_on?: (number) | null
  eapt: string
  eut?: (string) | null
  faft?: (string) | null
  fut?: (string) | null
  gapt?: (string) | null
  /**
   * @default 0
   */
  garage_category?: (number) | null
  gut?: (string) | null
  iaft?: (string) | null
  iut?: (string) | null
  jaft?: (string) | null
  jut?: (string) | null
  /**
   * @default 0
   */
  modified_rule?: (number) | null
  parent_abstract_part_type_id?: (number) | null
  part_filename?: (string) | null
  /**
   * @default 0
   */
  part_paired?: (number) | null
  /**
   * @default 0
   */
  repair_cost_modifier?: (string) | null
  saft?: (string) | null
  schematic_picname1?: (string) | null
  schematic_picname2?: (string) | null
  /**
   * @default 0
   */
  scrap_value_modifier?: (string) | null
  sut?: (string) | null
  sw_aft?: (string) | null
  swut?: (string) | null
}
export type {AbstractPartType_InsertParameters}
