/**
 * !!! This file is autogenerated do not edit by hand !!!
 *
 * Generated by: @databases/pg-schema-print-types
 * Checksum: WsmDmKvwU+poIX0iFyB7Bz5NyR4Fm9VrG2x3f4c3JAwWc31YsLU4jiLx+9kHFzICeXSQYvdlpaLUEDPCGjMv+g==
 */

/* eslint-disable */
// tslint:disable

interface AtdatabasesMigrationsApplied {
  applied_at: Date
  /**
   * @default nextval('atdatabases_migrations_applied_id_seq'::regclass)
   */
  id: number & {readonly __brand?: 'atdatabases_migrations_applied_id'}
  ignored_error: (string) | null
  index: number
  name: string
  obsolete: boolean
  script: string
}
export default AtdatabasesMigrationsApplied;

interface AtdatabasesMigrationsApplied_InsertParameters {
  applied_at: Date
  /**
   * @default nextval('atdatabases_migrations_applied_id_seq'::regclass)
   */
  id?: number & {readonly __brand?: 'atdatabases_migrations_applied_id'}
  ignored_error?: (string) | null
  index: number
  name: string
  obsolete: boolean
  script: string
}
export type {AtdatabasesMigrationsApplied_InsertParameters}
