/**
 * !!! This file is autogenerated do not edit by hand !!!
 *
 * Generated by: @databases/pg-schema-print-types
 * Checksum: M8/YeSSGw/7qUaLSrfbNooJeHfkjY6i8wHalJSCCjZyADA5nkk9+voEpAQfQJOdg7cNlnxivhPF6qgfyE3cFgA==
 */

/* eslint-disable */
// tslint:disable

interface AttachmentPoint {
  attachment_point: string
  attachment_point_id: number & {readonly __brand?: 'attachment_point_attachment_point_id'}
}
export default AttachmentPoint;

interface AttachmentPoint_InsertParameters {
  attachment_point: string
  attachment_point_id: number & {readonly __brand?: 'attachment_point_attachment_point_id'}
}
export type {AttachmentPoint_InsertParameters}
