/**
 * !!! This file is autogenerated do not edit by hand !!!
 *
 * Generated by: @databases/pg-schema-print-types
 * Checksum: 5+uzmr7yCLCXynf+ykB59Q6WCsFKvE5CITtT72DJC1xt3sMAQVveNbFQXfbXlAcX9C5B3rkf3ngCkoUik4pp7g==
 */

/* eslint-disable */
// tslint:disable

interface Brand {
  brand: (string) | null
  brand_id: number & {readonly __brand?: 'brand_brand_id'}
  /**
   * @default 0
   */
  is_stock: (number) | null
  pic_name: (string) | null
}
export default Brand;

interface Brand_InsertParameters {
  brand?: (string) | null
  brand_id: number & {readonly __brand?: 'brand_brand_id'}
  /**
   * @default 0
   */
  is_stock?: (number) | null
  pic_name?: (string) | null
}
export type {Brand_InsertParameters}
