/**
 * !!! This file is autogenerated do not edit by hand !!!
 *
 * Generated by: @databases/pg-schema-print-types
 * Checksum: FO1yVOHkrUQOwgs9QB7W4cjJTnhjXQ/AMtegydVJKYAy6IrWZfobFOsHnQZkd9wBwKOr3ZsMe0f6wPTHye3Tgg==
 */

/* eslint-disable */
// tslint:disable

import Model from './model'
import PartType from './part_type'

interface BrandedPart {
  branded_part_id: number & {readonly __brand?: 'branded_part_branded_part_id'}
  /**
   * @default 0
   */
  engine_block_family_id: number
  max_item_wear: (number) | null
  mfg_date: Date
  model_id: Model['model_id']
  part_type_id: PartType['part_type_id']
  qty_avail: number
  retail_price: number
}
export default BrandedPart;

interface BrandedPart_InsertParameters {
  branded_part_id: number & {readonly __brand?: 'branded_part_branded_part_id'}
  /**
   * @default 0
   */
  engine_block_family_id?: number
  max_item_wear?: (number) | null
  mfg_date: Date
  model_id: Model['model_id']
  part_type_id: PartType['part_type_id']
  qty_avail: number
  retail_price: number
}
export type {BrandedPart_InsertParameters}
