/**
 * !!! This file is autogenerated do not edit by hand !!!
 *
 * Generated by: @databases/pg-schema-print-types
 * Checksum: /rudeJZZtDrBYSXjgXr5S4CVYtvkdViVwr6GIhs0pflzGzXgzecKQWMu5xwCJjnceOeZlC+VzWGubFzI2+lIkQ==
 */

/* eslint-disable */
// tslint:disable

interface DriverClass {
  driver_class: (string) | null
  driver_class_id: number & {readonly __brand?: 'driver_class_driver_class_id'}
}
export default DriverClass;

interface DriverClass_InsertParameters {
  driver_class?: (string) | null
  driver_class_id: number & {readonly __brand?: 'driver_class_driver_class_id'}
}
export type {DriverClass_InsertParameters}
