// @ts-nocheck
/**
 * !!! This file is autogenerated do not edit by hand !!!
 *
 * Generated by: @databases/pg-schema-print-types
 * Checksum: HmcQAYW57lGg5VHkzZd5mwdgjn+VZIEF7psh5km4DkEA2MK6n4n0KNTWfDT2B4c6gDnpnLoVvIjK8bEDGASVXw==
 */

/* eslint-disable */
// tslint:disable

interface GooseDbVersion {
  id: number & {readonly __brand?: 'goose_db_version_id'}
  is_applied: boolean
  /**
   * @default now()
   */
  tstamp: Date
  version_id: number
}
export default GooseDbVersion;

interface GooseDbVersion_InsertParameters {
  id: number & {readonly __brand?: 'goose_db_version_id'}
  is_applied: boolean
  /**
   * @default now()
   */
  tstamp?: Date
  version_id: number
}
export type {GooseDbVersion_InsertParameters}
