// @ts-nocheck
/**
 * !!! This file is autogenerated do not edit by hand !!!
 *
 * Generated by: @databases/pg-schema-print-types
 * Checksum: Ylj3PzItoWkwT9uKJlD+/yWnnp1m6pLQs2kQz1X3tFgjcgi1YMclPThJmJRN8eBToNUsqhTES5GmJpH+YBNNnA==
 */

/* eslint-disable */
// tslint:disable

import type AbstractPartType from './abstract_part_type'
import type {AbstractPartType_InsertParameters} from './abstract_part_type'
import type AtdatabasesMigrationsApplied from './atdatabases_migrations_applied'
import type {AtdatabasesMigrationsApplied_InsertParameters} from './atdatabases_migrations_applied'
import type AtdatabasesMigrationsVersion from './atdatabases_migrations_version'
import type {AtdatabasesMigrationsVersion_InsertParameters} from './atdatabases_migrations_version'
import type AttachmentPoint from './attachment_point'
import type {AttachmentPoint_InsertParameters} from './attachment_point'
import type Brand from './brand'
import type {Brand_InsertParameters} from './brand'
import type BrandedPart from './branded_part'
import type {BrandedPart_InsertParameters} from './branded_part'
import type DriverClass from './driver_class'
import type {DriverClass_InsertParameters} from './driver_class'
import type GooseDbVersion from './goose_db_version'
import type {GooseDbVersion_InsertParameters} from './goose_db_version'
import type Key from './key'
import type {Key_InsertParameters} from './key'
import type Login from './login'
import type {Login_InsertParameters} from './login'
import type Model from './model'
import type {Model_InsertParameters} from './model'
import type Part from './part'
import type {Part_InsertParameters} from './part'
import type PartGrade from './part_grade'
import type {PartGrade_InsertParameters} from './part_grade'
import type PartType from './part_type'
import type {PartType_InsertParameters} from './part_type'
import type Player from './player'
import type {Player_InsertParameters} from './player'
import type PlayerType from './player_type'
import type {PlayerType_InsertParameters} from './player_type'
import type Profile from './profile'
import type {Profile_InsertParameters} from './profile'
import type PtSkin from './pt_skin'
import type {PtSkin_InsertParameters} from './pt_skin'
import type SkinType from './skin_type'
import type {SkinType_InsertParameters} from './skin_type'
import type StockAssembly from './stock_assembly'
import type {StockAssembly_InsertParameters} from './stock_assembly'
import type StockVehicleAttributes from './stock_vehicle_attributes'
import type {StockVehicleAttributes_InsertParameters} from './stock_vehicle_attributes'
import type SvaCarClass from './sva_car_class'
import type {SvaCarClass_InsertParameters} from './sva_car_class'
import type SvaModeRestriction from './sva_mode_restriction'
import type {SvaModeRestriction_InsertParameters} from './sva_mode_restriction'
import type Vehicle from './vehicle'
import type {Vehicle_InsertParameters} from './vehicle'
import type Warehouse from './warehouse'
import type {Warehouse_InsertParameters} from './warehouse'

interface DatabaseSchema {
  abstract_part_type: {record: AbstractPartType, insert: AbstractPartType_InsertParameters};
  atdatabases_migrations_applied: {record: AtdatabasesMigrationsApplied, insert: AtdatabasesMigrationsApplied_InsertParameters};
  atdatabases_migrations_version: {record: AtdatabasesMigrationsVersion, insert: AtdatabasesMigrationsVersion_InsertParameters};
  attachment_point: {record: AttachmentPoint, insert: AttachmentPoint_InsertParameters};
  brand: {record: Brand, insert: Brand_InsertParameters};
  branded_part: {record: BrandedPart, insert: BrandedPart_InsertParameters};
  driver_class: {record: DriverClass, insert: DriverClass_InsertParameters};
  goose_db_version: {record: GooseDbVersion, insert: GooseDbVersion_InsertParameters};
  key: {record: Key, insert: Key_InsertParameters};
  login: {record: Login, insert: Login_InsertParameters};
  model: {record: Model, insert: Model_InsertParameters};
  part: {record: Part, insert: Part_InsertParameters};
  part_grade: {record: PartGrade, insert: PartGrade_InsertParameters};
  part_type: {record: PartType, insert: PartType_InsertParameters};
  player: {record: Player, insert: Player_InsertParameters};
  player_type: {record: PlayerType, insert: PlayerType_InsertParameters};
  profile: {record: Profile, insert: Profile_InsertParameters};
  pt_skin: {record: PtSkin, insert: PtSkin_InsertParameters};
  skin_type: {record: SkinType, insert: SkinType_InsertParameters};
  stock_assembly: {record: StockAssembly, insert: StockAssembly_InsertParameters};
  stock_vehicle_attributes: {record: StockVehicleAttributes, insert: StockVehicleAttributes_InsertParameters};
  sva_car_class: {record: SvaCarClass, insert: SvaCarClass_InsertParameters};
  sva_mode_restriction: {record: SvaModeRestriction, insert: SvaModeRestriction_InsertParameters};
  vehicle: {record: Vehicle, insert: Vehicle_InsertParameters};
  warehouse: {record: Warehouse, insert: Warehouse_InsertParameters};
}
export default DatabaseSchema;

function serializeValue(_tableName: string, _columnName: string, value: unknown): unknown {
  return value;
}
export {serializeValue}

export type {
  AbstractPartType,
  AbstractPartType_InsertParameters,
  AtdatabasesMigrationsApplied,
  AtdatabasesMigrationsApplied_InsertParameters,
  AtdatabasesMigrationsVersion,
  AtdatabasesMigrationsVersion_InsertParameters,
  AttachmentPoint,
  AttachmentPoint_InsertParameters,
  Brand,
  Brand_InsertParameters,
  BrandedPart,
  BrandedPart_InsertParameters,
  DriverClass,
  DriverClass_InsertParameters,
  GooseDbVersion,
  GooseDbVersion_InsertParameters,
  Key,
  Key_InsertParameters,
  Login,
  Login_InsertParameters,
  Model,
  Model_InsertParameters,
  Part,
  PartGrade,
  PartGrade_InsertParameters,
  PartType,
  PartType_InsertParameters,
  Part_InsertParameters,
  Player,
  PlayerType,
  PlayerType_InsertParameters,
  Player_InsertParameters,
  Profile,
  Profile_InsertParameters,
  PtSkin,
  PtSkin_InsertParameters,
  SkinType,
  SkinType_InsertParameters,
  StockAssembly,
  StockAssembly_InsertParameters,
  StockVehicleAttributes,
  StockVehicleAttributes_InsertParameters,
  SvaCarClass,
  SvaCarClass_InsertParameters,
  SvaModeRestriction,
  SvaModeRestriction_InsertParameters,
  Vehicle,
  Vehicle_InsertParameters,
  Warehouse,
  Warehouse_InsertParameters,
}
