/**
 * !!! This file is autogenerated do not edit by hand !!!
 *
 * Generated by: @databases/pg-schema-print-types
 * Checksum: vxwlgkHcVcRZFiTangk9H5WwLqrSWEy51UAfux9QlDfymxXNN3xR7TOK5QunZFk/8dPN8gpKona6QErjHlBLvA==
 */

/* eslint-disable */
// tslint:disable

import AbstractPartType, {AbstractPartType_InsertParameters} from './abstract_part_type'
import AtdatabasesMigrationsApplied, {AtdatabasesMigrationsApplied_InsertParameters} from './atdatabases_migrations_applied'
import AtdatabasesMigrationsVersion, {AtdatabasesMigrationsVersion_InsertParameters} from './atdatabases_migrations_version'
import AttachmentPoint, {AttachmentPoint_InsertParameters} from './attachment_point'
import Brand, {Brand_InsertParameters} from './brand'
import BrandedPart, {BrandedPart_InsertParameters} from './branded_part'
import DriverClass, {DriverClass_InsertParameters} from './driver_class'
import Key, {Key_InsertParameters} from './key'
import Login, {Login_InsertParameters} from './login'
import Model, {Model_InsertParameters} from './model'
import Part, {Part_InsertParameters} from './part'
import PartGrade, {PartGrade_InsertParameters} from './part_grade'
import PartType, {PartType_InsertParameters} from './part_type'
import Player, {Player_InsertParameters} from './player'
import PlayerType, {PlayerType_InsertParameters} from './player_type'
import Profile, {Profile_InsertParameters} from './profile'
import PtSkin, {PtSkin_InsertParameters} from './pt_skin'
import SkinType, {SkinType_InsertParameters} from './skin_type'
import StockAssembly, {StockAssembly_InsertParameters} from './stock_assembly'
import StockVehicleAttributes, {StockVehicleAttributes_InsertParameters} from './stock_vehicle_attributes'
import SvaCarClass, {SvaCarClass_InsertParameters} from './sva_car_class'
import SvaModeRestriction, {SvaModeRestriction_InsertParameters} from './sva_mode_restriction'
import Vehicle, {Vehicle_InsertParameters} from './vehicle'
import Warehouse, {Warehouse_InsertParameters} from './warehouse'

interface DatabaseSchema {
  abstract_part_type: {record: AbstractPartType, insert: AbstractPartType_InsertParameters};
  atdatabases_migrations_applied: {record: AtdatabasesMigrationsApplied, insert: AtdatabasesMigrationsApplied_InsertParameters};
  atdatabases_migrations_version: {record: AtdatabasesMigrationsVersion, insert: AtdatabasesMigrationsVersion_InsertParameters};
  attachment_point: {record: AttachmentPoint, insert: AttachmentPoint_InsertParameters};
  brand: {record: Brand, insert: Brand_InsertParameters};
  branded_part: {record: BrandedPart, insert: BrandedPart_InsertParameters};
  driver_class: {record: DriverClass, insert: DriverClass_InsertParameters};
  key: {record: Key, insert: Key_InsertParameters};
  login: {record: Login, insert: Login_InsertParameters};
  model: {record: Model, insert: Model_InsertParameters};
  part: {record: Part, insert: Part_InsertParameters};
  part_grade: {record: PartGrade, insert: PartGrade_InsertParameters};
  part_type: {record: PartType, insert: PartType_InsertParameters};
  player: {record: Player, insert: Player_InsertParameters};
  player_type: {record: PlayerType, insert: PlayerType_InsertParameters};
  profile: {record: Profile, insert: Profile_InsertParameters};
  pt_skin: {record: PtSkin, insert: PtSkin_InsertParameters};
  skin_type: {record: SkinType, insert: SkinType_InsertParameters};
  stock_assembly: {record: StockAssembly, insert: StockAssembly_InsertParameters};
  stock_vehicle_attributes: {record: StockVehicleAttributes, insert: StockVehicleAttributes_InsertParameters};
  sva_car_class: {record: SvaCarClass, insert: SvaCarClass_InsertParameters};
  sva_mode_restriction: {record: SvaModeRestriction, insert: SvaModeRestriction_InsertParameters};
  vehicle: {record: Vehicle, insert: Vehicle_InsertParameters};
  warehouse: {record: Warehouse, insert: Warehouse_InsertParameters};
}
export default DatabaseSchema;

function serializeValue(_tableName: string, _columnName: string, value: unknown): unknown {
  return value;
}
export {serializeValue}

export type {
  AbstractPartType,
  AbstractPartType_InsertParameters,
  AtdatabasesMigrationsApplied,
  AtdatabasesMigrationsApplied_InsertParameters,
  AtdatabasesMigrationsVersion,
  AtdatabasesMigrationsVersion_InsertParameters,
  AttachmentPoint,
  AttachmentPoint_InsertParameters,
  Brand,
  Brand_InsertParameters,
  BrandedPart,
  BrandedPart_InsertParameters,
  DriverClass,
  DriverClass_InsertParameters,
  Key,
  Key_InsertParameters,
  Login,
  Login_InsertParameters,
  Model,
  Model_InsertParameters,
  Part,
  PartGrade,
  PartGrade_InsertParameters,
  PartType,
  PartType_InsertParameters,
  Part_InsertParameters,
  Player,
  PlayerType,
  PlayerType_InsertParameters,
  Player_InsertParameters,
  Profile,
  Profile_InsertParameters,
  PtSkin,
  PtSkin_InsertParameters,
  SkinType,
  SkinType_InsertParameters,
  StockAssembly,
  StockAssembly_InsertParameters,
  StockVehicleAttributes,
  StockVehicleAttributes_InsertParameters,
  SvaCarClass,
  SvaCarClass_InsertParameters,
  SvaModeRestriction,
  SvaModeRestriction_InsertParameters,
  Vehicle,
  Vehicle_InsertParameters,
  Warehouse,
  Warehouse_InsertParameters,
}
