/**
 * !!! This file is autogenerated do not edit by hand !!!
 *
 * Generated by: @databases/pg-schema-print-types
 * Checksum: wgW746gZo7mof5uc2ai7LDQ1itqPc0/zYJtvjUJry8MpivFZUjS7WiUbKX3lPoYnAt873cAiDJCAv58CAn/6ag==
 */

/* eslint-disable */
// tslint:disable

import Profile from './profile'

interface Key {
  profile_id: Profile['profile_id']
  session_key: string
}
export default Key;

interface Key_InsertParameters {
  profile_id: Profile['profile_id']
  session_key: string
}
export type {Key_InsertParameters}
