/**
 * !!! This file is autogenerated do not edit by hand !!!
 *
 * Generated by: @databases/pg-schema-print-types
 * Checksum: jI7CFo4ToJ0njsv1Nz5ic3WC9Jh90718YRYWBe5SCUPkw4duMKQ+yAkyt0dwDDcaSCIrm3sW7/sFgWEzRmbj5A==
 */

/* eslint-disable */
// tslint:disable

interface Login {
  customer_id: number
  /**
   * @default 0
   */
  login_level: number
  login_name: string & {readonly __brand?: 'login_login_name'}
  password: string
}
export default Login;

interface Login_InsertParameters {
  customer_id: number
  /**
   * @default 0
   */
  login_level?: number
  login_name: string & {readonly __brand?: 'login_login_name'}
  password: string
}
export type {Login_InsertParameters}
