/**
 * !!! This file is autogenerated do not edit by hand !!!
 *
 * Generated by: @databases/pg-schema-print-types
 * Checksum: Qq9KWzMs7h2M97USxqjonfltR7XxApLJj5Pvd4uVFMSfGJOfu1D1g8DKiqqA/tJl1FHx4ioQk4VTEWuwTHbuig==
 */

/* eslint-disable */
// tslint:disable

import Brand from './brand'

interface Model {
  b_extra_info: (string) | null
  b_model: (string) | null
  b_short_model: (string) | null
  brand_id: Brand['brand_id']
  debug_sort_string: (string) | null
  debug_string: (string) | null
  e_extra_info: (string) | null
  e_model: (string) | null
  e_short_model: (string) | null
  f_extra_info: (string) | null
  f_model: (string) | null
  f_short_model: (string) | null
  g_extra_info: (string) | null
  g_model: (string) | null
  g_short_model: (string) | null
  i_extra_info: (string) | null
  i_model: (string) | null
  i_short_model: (string) | null
  j_extra_info: (string) | null
  j_model: (string) | null
  j_short_model: (string) | null
  model_id: number & {readonly __brand?: 'model_model_id'}
  s_extra_info: (string) | null
  s_model: (string) | null
  s_short_model: (string) | null
  sw_extra_info: (string) | null
  sw_model: (string) | null
  sw_short_model: (string) | null
}
export default Model;

interface Model_InsertParameters {
  b_extra_info?: (string) | null
  b_model?: (string) | null
  b_short_model?: (string) | null
  brand_id: Brand['brand_id']
  debug_sort_string?: (string) | null
  debug_string?: (string) | null
  e_extra_info?: (string) | null
  e_model?: (string) | null
  e_short_model?: (string) | null
  f_extra_info?: (string) | null
  f_model?: (string) | null
  f_short_model?: (string) | null
  g_extra_info?: (string) | null
  g_model?: (string) | null
  g_short_model?: (string) | null
  i_extra_info?: (string) | null
  i_model?: (string) | null
  i_short_model?: (string) | null
  j_extra_info?: (string) | null
  j_model?: (string) | null
  j_short_model?: (string) | null
  model_id: number & {readonly __brand?: 'model_model_id'}
  s_extra_info?: (string) | null
  s_model?: (string) | null
  s_short_model?: (string) | null
  sw_extra_info?: (string) | null
  sw_model?: (string) | null
  sw_short_model?: (string) | null
}
export type {Model_InsertParameters}
