/**
 * !!! This file is autogenerated do not edit by hand !!!
 *
 * Generated by: @databases/pg-schema-print-types
 * Checksum: r6ugbodeJS+NyD2EV4tEiehaMPdc6JlFSQdwqPL8rhK6qnoLI+5Oqhnf70/4q7v27LqZj18o9u0QljUK+3gDfg==
 */

/* eslint-disable */
// tslint:disable

import AttachmentPoint from './attachment_point'
import BrandedPart from './branded_part'

interface Part {
  attachment_point_id: (AttachmentPoint['attachment_point_id']) | null
  branded_part_id: BrandedPart['branded_part_id']
  item_wear: number
  owner_id: (number) | null
  parent_part_id: (number) | null
  part_id: number & {readonly __brand?: 'part_part_id'}
  part_name: (string) | null
  percent_damage: number
  /**
   * @default 0
   */
  repair_cost: (number) | null
  /**
   * @default 0
   */
  scrap_value: (number) | null
}
export default Part;

interface Part_InsertParameters {
  attachment_point_id?: (AttachmentPoint['attachment_point_id']) | null
  branded_part_id: BrandedPart['branded_part_id']
  item_wear: number
  owner_id?: (number) | null
  parent_part_id?: (number) | null
  part_id: number & {readonly __brand?: 'part_part_id'}
  part_name?: (string) | null
  percent_damage: number
  /**
   * @default 0
   */
  repair_cost?: (number) | null
  /**
   * @default 0
   */
  scrap_value?: (number) | null
}
export type {Part_InsertParameters}
