/**
 * !!! This file is autogenerated do not edit by hand !!!
 *
 * Generated by: @databases/pg-schema-print-types
 * Checksum: llTnc44yDeEt4bCekTPJhS5xGIfL3IuJzgPaGSWsm0DRRZSILUEfEvpaLFnlNFe+ZUgYQgph9p/Sx5zW/rvryg==
 */

/* eslint-disable */
// tslint:disable

interface PartGrade {
  e_text: (string) | null
  f_text: (string) | null
  g_text: (string) | null
  part_grade: (string) | null
  part_grade_id: number & {readonly __brand?: 'part_grade_part_grade_id'}
}
export default PartGrade;

interface PartGrade_InsertParameters {
  e_text?: (string) | null
  f_text?: (string) | null
  g_text?: (string) | null
  part_grade?: (string) | null
  part_grade_id: number & {readonly __brand?: 'part_grade_part_grade_id'}
}
export type {PartGrade_InsertParameters}
