/**
 * !!! This file is autogenerated do not edit by hand !!!
 *
 * Generated by: @databases/pg-schema-print-types
 * Checksum: Vn4sM7SA51T3U0kn74/QGtOKnsmDine+eesJkqom/sgJrJ45gWOsqMmzm/bx4TP6ut8x8SeBjRywUa7D8S3Kzg==
 */

/* eslint-disable */
// tslint:disable

interface PlayerType {
  player_type: string
  player_type_id: number & {readonly __brand?: 'player_type_player_type_id'}
}
export default PlayerType;

interface PlayerType_InsertParameters {
  player_type: string
  player_type_id: number & {readonly __brand?: 'player_type_player_type_id'}
}
export type {PlayerType_InsertParameters}
