/**
 * !!! This file is autogenerated do not edit by hand !!!
 *
 * Generated by: @databases/pg-schema-print-types
 * Checksum: gKn2soAeVAuhf3iovJDOurssIFodyk5OHPYCE9NgAM+k3DmAM70ATZUjes0HKRpBAhJLsmyFmUehysYOSriHHw==
 */

/* eslint-disable */
// tslint:disable

import DriverClass from './driver_class'
import PlayerType from './player_type'

interface Player {
  address: (string) | null
  bank_balance: number
  /**
   * @default 0
   */
  body_type: (number) | null
  car_info_setting: (number) | null
  car_num1: string
  car_num2: string
  car_num3: string
  car_num4: string
  car_num5: string
  car_num6: string
  /**
   * @default 0
   */
  cars_lost: (number) | null
  /**
   * @default 0
   */
  cars_won: (number) | null
  /**
   * @default 0
   */
  challenge_races_completed: (number) | null
  /**
   * @default 0
   */
  challenge_races_run: (number) | null
  /**
   * @default 0
   */
  challenge_races_won: (number) | null
  challenge_rung: (number) | null
  challenge_score: (number) | null
  current_race_id: (number) | null
  customer_id: number
  dl_number: (string) | null
  drag_class: (DriverClass['driver_class_id']) | null
  driver_style: number
  /**
   * @default 0
   */
  evaded_fuzz: (number) | null
  /**
   * @default 0
   */
  hair_color: (number) | null
  /**
   * @default 0
   */
  insurance_rating: (number) | null
  /**
   * @default 0
   */
  insurance_risk_points: (number) | null
  is_logged_in: (number) | null
  last_logged_in: (Date) | null
  lp_code: number
  lp_text: (string) | null
  modified_classic_class: (DriverClass['driver_class_id']) | null
  modified_muscle_class: (DriverClass['driver_class_id']) | null
  num_cars_owned: number
  /**
   * @default 0
   */
  num_unread_mail: (number) | null
  /**
   * @default 0
   */
  offline_ai_car_bpt_id: (number) | null
  /**
   * @default 0
   */
  offline_ai_car_class: (number) | null
  /**
   * @default 0
   */
  offline_ai_skin_id: (number) | null
  /**
   * @default 0
   */
  offline_ai_state: (number) | null
  offline_driver_attitude: (number) | null
  offline_driver_skill: (number) | null
  offline_driver_style: (number) | null
  offline_grudge: (number) | null
  offline_reputation: (number) | null
  outlaw_class: (DriverClass['driver_class_id']) | null
  /**
   * @default 0
   */
  pants_color: (number) | null
  persona: string
  /**
   * @default 0
   */
  pinks_won: (number) | null
  player_id: number & {readonly __brand?: 'player_player_id'}
  player_type_id: PlayerType['player_type_id']
  residence: (string) | null
  sanctioned_score: (number) | null
  /**
   * @default 0
   */
  shirt_color: (number) | null
  /**
   * @default 0
   */
  skin_color: (number) | null
  stock_classic_class: (number) | null
  stock_muscle_class: (DriverClass['driver_class_id']) | null
  times_logged_in: (number) | null
  /**
   * @default 0
   */
  total_races_completed: (number) | null
  /**
   * @default 0
   */
  total_races_run: (number) | null
  /**
   * @default 0
   */
  total_races_won: (number) | null
  total_time_played: (number) | null
  /**
   * @default 0
   */
  total_winnings: (number) | null
  vehicle_id: (number) | null
}
export default Player;

interface Player_InsertParameters {
  address?: (string) | null
  bank_balance: number
  /**
   * @default 0
   */
  body_type?: (number) | null
  car_info_setting?: (number) | null
  car_num1: string
  car_num2: string
  car_num3: string
  car_num4: string
  car_num5: string
  car_num6: string
  /**
   * @default 0
   */
  cars_lost?: (number) | null
  /**
   * @default 0
   */
  cars_won?: (number) | null
  /**
   * @default 0
   */
  challenge_races_completed?: (number) | null
  /**
   * @default 0
   */
  challenge_races_run?: (number) | null
  /**
   * @default 0
   */
  challenge_races_won?: (number) | null
  challenge_rung?: (number) | null
  challenge_score?: (number) | null
  current_race_id?: (number) | null
  customer_id: number
  dl_number?: (string) | null
  drag_class?: (DriverClass['driver_class_id']) | null
  driver_style: number
  /**
   * @default 0
   */
  evaded_fuzz?: (number) | null
  /**
   * @default 0
   */
  hair_color?: (number) | null
  /**
   * @default 0
   */
  insurance_rating?: (number) | null
  /**
   * @default 0
   */
  insurance_risk_points?: (number) | null
  is_logged_in?: (number) | null
  last_logged_in?: (Date) | null
  lp_code: number
  lp_text?: (string) | null
  modified_classic_class?: (DriverClass['driver_class_id']) | null
  modified_muscle_class?: (DriverClass['driver_class_id']) | null
  num_cars_owned: number
  /**
   * @default 0
   */
  num_unread_mail?: (number) | null
  /**
   * @default 0
   */
  offline_ai_car_bpt_id?: (number) | null
  /**
   * @default 0
   */
  offline_ai_car_class?: (number) | null
  /**
   * @default 0
   */
  offline_ai_skin_id?: (number) | null
  /**
   * @default 0
   */
  offline_ai_state?: (number) | null
  offline_driver_attitude?: (number) | null
  offline_driver_skill?: (number) | null
  offline_driver_style?: (number) | null
  offline_grudge?: (number) | null
  offline_reputation?: (number) | null
  outlaw_class?: (DriverClass['driver_class_id']) | null
  /**
   * @default 0
   */
  pants_color?: (number) | null
  persona: string
  /**
   * @default 0
   */
  pinks_won?: (number) | null
  player_id: number & {readonly __brand?: 'player_player_id'}
  player_type_id: PlayerType['player_type_id']
  residence?: (string) | null
  sanctioned_score?: (number) | null
  /**
   * @default 0
   */
  shirt_color?: (number) | null
  /**
   * @default 0
   */
  skin_color?: (number) | null
  stock_classic_class?: (number) | null
  stock_muscle_class?: (DriverClass['driver_class_id']) | null
  times_logged_in?: (number) | null
  /**
   * @default 0
   */
  total_races_completed?: (number) | null
  /**
   * @default 0
   */
  total_races_run?: (number) | null
  /**
   * @default 0
   */
  total_races_won?: (number) | null
  total_time_played?: (number) | null
  /**
   * @default 0
   */
  total_winnings?: (number) | null
  vehicle_id?: (number) | null
}
export type {Player_InsertParameters}
