/**
 * !!! This file is autogenerated do not edit by hand !!!
 *
 * Generated by: @databases/pg-schema-print-types
 * Checksum: K5z3NAJNi7LjL4o2EgNAi4QT6I+QWNd4TXWcycmzlohj/F2l9sUIxjZds/2EF5SuNb/Huo65020zv4EuLdWHZA==
 */

/* eslint-disable */
// tslint:disable

interface Profile {
  /**
   * @default EXTRACT(epoch FROM now())::integer
   */
  create_stamp: number
  current_key: string
  customer_id: number
  /**
   * @default false
   */
  dnd: boolean
  game_blob: string
  /**
   * @default EXTRACT(epoch FROM now())::integer
   */
  game_purchase_stamp: number
  game_serial_number: string
  /**
   * @default EXTRACT(epoch FROM now())::integer
   */
  game_start_stamp: number
  /**
   * @default false
   */
  is_online: boolean
  /**
   * @default EXTRACT(epoch FROM now())::integer
   */
  last_login_stamp: number
  /**
   * @default 1
   */
  number_games: number
  personal_blob: string
  picture_blob: string
  profile_id: number & {readonly __brand?: 'profile_profile_id'}
  /**
   * @default 0
   */
  profile_level: number
  profile_name: string
  /**
   * @default 0
   */
  server_id: number
  shard_id: number
  time_in_game: number
  time_online: number
}
export default Profile;

interface Profile_InsertParameters {
  /**
   * @default EXTRACT(epoch FROM now())::integer
   */
  create_stamp?: number
  current_key: string
  customer_id: number
  /**
   * @default false
   */
  dnd?: boolean
  game_blob: string
  /**
   * @default EXTRACT(epoch FROM now())::integer
   */
  game_purchase_stamp?: number
  game_serial_number: string
  /**
   * @default EXTRACT(epoch FROM now())::integer
   */
  game_start_stamp?: number
  /**
   * @default false
   */
  is_online?: boolean
  /**
   * @default EXTRACT(epoch FROM now())::integer
   */
  last_login_stamp?: number
  /**
   * @default 1
   */
  number_games?: number
  personal_blob: string
  picture_blob: string
  profile_id: number & {readonly __brand?: 'profile_profile_id'}
  /**
   * @default 0
   */
  profile_level?: number
  profile_name: string
  /**
   * @default 0
   */
  server_id?: number
  shard_id: number
  time_in_game: number
  time_online: number
}
export type {Profile_InsertParameters}
