/**
 * !!! This file is autogenerated do not edit by hand !!!
 *
 * Generated by: @databases/pg-schema-print-types
 * Checksum: 0TdVdR0Di4kkCqeXSWPevxew/lFqzaq7QWD9ti0m3cUx1KZd395xLCLnKHWkuRJ7ZhMVwS6YIGMmgvRjEbCH7Q==
 */

/* eslint-disable */
// tslint:disable

import PartType from './part_type'
import SkinType from './skin_type'

interface PtSkin {
  b_skin: (string) | null
  c0: (number) | null
  c1: (number) | null
  c2: (number) | null
  c3: (number) | null
  c4: (number) | null
  c5: (number) | null
  c6: (number) | null
  c7: (number) | null
  comment_text: (string) | null
  creator_id: (number) | null
  creator_name: (string) | null
  /**
   * @default 0
   */
  default_flag: (number) | null
  e_skin: (string) | null
  f_skin: (string) | null
  g_skin: (string) | null
  h0: (number) | null
  h1: (number) | null
  h2: (number) | null
  h3: (number) | null
  h4: (number) | null
  h5: (number) | null
  h6: (number) | null
  h7: (number) | null
  i_skin: (string) | null
  j_skin: (string) | null
  part_filename: (string) | null
  part_type_id: (PartType['part_type_id']) | null
  price: number
  s0: (number) | null
  s1: (number) | null
  s2: (number) | null
  s3: (number) | null
  s4: (number) | null
  s5: (number) | null
  s6: (number) | null
  s7: (number) | null
  s_skin: (string) | null
  skin_id: number & {readonly __brand?: 'pt_skin_skin_id'}
  skin_type_id: (SkinType['skin_type_id']) | null
  sw_skin: (string) | null
  v0: (number) | null
  v1: (number) | null
  v2: (number) | null
  v3: (number) | null
  v4: (number) | null
  v5: (number) | null
  v6: (number) | null
  v7: (number) | null
  x0: (number) | null
  x1: (number) | null
  x2: (number) | null
  x3: (number) | null
  x4: (number) | null
  x5: (number) | null
  x6: (number) | null
  x7: (number) | null
  y0: (number) | null
  y1: (number) | null
  y2: (number) | null
  y3: (number) | null
  y4: (number) | null
  y5: (number) | null
  y6: (number) | null
  y7: (number) | null
}
export default PtSkin;

interface PtSkin_InsertParameters {
  b_skin?: (string) | null
  c0?: (number) | null
  c1?: (number) | null
  c2?: (number) | null
  c3?: (number) | null
  c4?: (number) | null
  c5?: (number) | null
  c6?: (number) | null
  c7?: (number) | null
  comment_text?: (string) | null
  creator_id?: (number) | null
  creator_name?: (string) | null
  /**
   * @default 0
   */
  default_flag?: (number) | null
  e_skin?: (string) | null
  f_skin?: (string) | null
  g_skin?: (string) | null
  h0?: (number) | null
  h1?: (number) | null
  h2?: (number) | null
  h3?: (number) | null
  h4?: (number) | null
  h5?: (number) | null
  h6?: (number) | null
  h7?: (number) | null
  i_skin?: (string) | null
  j_skin?: (string) | null
  part_filename?: (string) | null
  part_type_id?: (PartType['part_type_id']) | null
  price: number
  s0?: (number) | null
  s1?: (number) | null
  s2?: (number) | null
  s3?: (number) | null
  s4?: (number) | null
  s5?: (number) | null
  s6?: (number) | null
  s7?: (number) | null
  s_skin?: (string) | null
  skin_id: number & {readonly __brand?: 'pt_skin_skin_id'}
  skin_type_id?: (SkinType['skin_type_id']) | null
  sw_skin?: (string) | null
  v0?: (number) | null
  v1?: (number) | null
  v2?: (number) | null
  v3?: (number) | null
  v4?: (number) | null
  v5?: (number) | null
  v6?: (number) | null
  v7?: (number) | null
  x0?: (number) | null
  x1?: (number) | null
  x2?: (number) | null
  x3?: (number) | null
  x4?: (number) | null
  x5?: (number) | null
  x6?: (number) | null
  x7?: (number) | null
  y0?: (number) | null
  y1?: (number) | null
  y2?: (number) | null
  y3?: (number) | null
  y4?: (number) | null
  y5?: (number) | null
  y6?: (number) | null
  y7?: (number) | null
}
export type {PtSkin_InsertParameters}
