/**
 * !!! This file is autogenerated do not edit by hand !!!
 *
 * Generated by: @databases/pg-schema-print-types
 * Checksum: 0Y6j1hEBv9fFPPMUwE+dfDeQCI3GQ8v/xmiDD1EuaveC0FbiFG9tqgrPaJT/fNJzXdD0vwLwA7atS6SbNZ7L+w==
 */

/* eslint-disable */
// tslint:disable

interface SkinType {
  skin_type: (string) | null
  skin_type_id: number & {readonly __brand?: 'skin_type_skin_type_id'}
}
export default SkinType;

interface SkinType_InsertParameters {
  skin_type?: (string) | null
  skin_type_id: number & {readonly __brand?: 'skin_type_skin_type_id'}
}
export type {SkinType_InsertParameters}
