/**
 * !!! This file is autogenerated do not edit by hand !!!
 *
 * Generated by: @databases/pg-schema-print-types
 * Checksum: eItxTTFjYW2AtKXc9YEk6zvsf1iP3TDsn/HvjbY3az8itICqa5H5p7WmuRh2uTVPeVHZtIRQ+HnboKRUmqHKdQ==
 */

/* eslint-disable */
// tslint:disable

import BrandedPart from './branded_part'
import SvaCarClass from './sva_car_class'
import SvaModeRestriction from './sva_mode_restriction'

interface StockVehicleAttributes {
  ai_restriction_class: (number) | null
  branded_part_id: BrandedPart['branded_part_id']
  car_class: (SvaCarClass['sva_car_class']) | null
  mode_restriction: (SvaModeRestriction['sva_mode_restriction']) | null
  /**
   * @default 1000
   */
  retail_price: (number) | null
  sponsor: (number) | null
  /**
   * @default 0
   */
  track_id: (number) | null
  vin_branded_part_id: (BrandedPart['branded_part_id']) | null
  /**
   * @default 0
   */
  vin_crc: number
}
export default StockVehicleAttributes;

interface StockVehicleAttributes_InsertParameters {
  ai_restriction_class?: (number) | null
  branded_part_id: BrandedPart['branded_part_id']
  car_class?: (SvaCarClass['sva_car_class']) | null
  mode_restriction?: (SvaModeRestriction['sva_mode_restriction']) | null
  /**
   * @default 1000
   */
  retail_price?: (number) | null
  sponsor?: (number) | null
  /**
   * @default 0
   */
  track_id?: (number) | null
  vin_branded_part_id?: (BrandedPart['branded_part_id']) | null
  /**
   * @default 0
   */
  vin_crc?: number
}
export type {StockVehicleAttributes_InsertParameters}
