/**
 * !!! This file is autogenerated do not edit by hand !!!
 *
 * Generated by: @databases/pg-schema-print-types
 * Checksum: jbNe73+qP3lZjMsdVB/t++M77bH6cRqj/wn8mV1Js8vMz7z4YSUn0TiJGKXG7LiVujgTHU4JwifPYc/8PFy4QA==
 */

/* eslint-disable */
// tslint:disable

interface SvaModeRestriction {
  description: (string) | null
  /**
   * @default 0
   */
  sva_mode_restriction: number & {readonly __brand?: 'sva_mode_restriction_sva_mode_restriction'}
}
export default SvaModeRestriction;

interface SvaModeRestriction_InsertParameters {
  description?: (string) | null
  /**
   * @default 0
   */
  sva_mode_restriction?: number & {readonly __brand?: 'sva_mode_restriction_sva_mode_restriction'}
}
export type {SvaModeRestriction_InsertParameters}
