/**
 * !!! This file is autogenerated do not edit by hand !!!
 *
 * Generated by: @databases/pg-schema-print-types
 * Checksum: Suo841IcTQeyyq7L+fPx9Tv+rUka791XOdAslmSWP7UJjw8IVSvTE2kE6aZEgG9TfwG7DaCRvrFrAVQZfHUBrw==
 */

/* eslint-disable */
// tslint:disable

interface SvaCarClass {
  description: (string) | null
  /**
   * @default 0
   */
  sva_car_class: number & {readonly __brand?: 'sva_car_class_sva_car_class'}
}
export default SvaCarClass;

interface SvaCarClass_InsertParameters {
  description?: (string) | null
  /**
   * @default 0
   */
  sva_car_class?: number & {readonly __brand?: 'sva_car_class_sva_car_class'}
}
export type {SvaCarClass_InsertParameters}
