/**
 * !!! This file is autogenerated do not edit by hand !!!
 *
 * Generated by: @databases/pg-schema-print-types
 * Checksum: erArmswP79+tT9kT7eo5CKZx8NL8IdmGOJ5mZBGIHWFnMLrwIJ+Sx5QJkgVJZlfPUSMYC4C4qPbsbbFEYSaMdQ==
 */

/* eslint-disable */
// tslint:disable

import Part from './part'
import PtSkin from './pt_skin'

interface Vehicle {
  class: number
  /**
   * @default 0
   */
  damage_cached: (number) | null
  damage_info: (Buffer) | null
  flags: number
  info_setting: number
  skin_id: PtSkin['skin_id']
  vehicle_id: Part['part_id']
}
export default Vehicle;

interface Vehicle_InsertParameters {
  class: number
  /**
   * @default 0
   */
  damage_cached?: (number) | null
  damage_info?: (Buffer) | null
  flags: number
  info_setting: number
  skin_id: PtSkin['skin_id']
  vehicle_id: Part['part_id']
}
export type {Vehicle_InsertParameters}
