/**
 * !!! This file is autogenerated do not edit by hand !!!
 *
 * Generated by: @databases/pg-schema-print-types
 * Checksum: XrOV3lTPYPS3btYlHuGZ0/mA/Tuj6CmNJE7ni+9dgYOjjKLKyNJG8NxmZ+/PG1R//a6U5DJR+ldmZ47r3E60Nw==
 */

/* eslint-disable */
// tslint:disable

interface Warehouse {
  branded_part_id: number & {readonly __brand?: 'warehouse_branded_part_id'}
  player_id: number & {readonly __brand?: 'warehouse_player_id'}
  qty_avail: (number) | null
  skin_id: number & {readonly __brand?: 'warehouse_skin_id'}
}
export default Warehouse;

interface Warehouse_InsertParameters {
  branded_part_id: number & {readonly __brand?: 'warehouse_branded_part_id'}
  player_id: number & {readonly __brand?: 'warehouse_player_id'}
  qty_avail?: (number) | null
  skin_id: number & {readonly __brand?: 'warehouse_skin_id'}
}
export type {Warehouse_InsertParameters}
